In [70]:
import pandas as pd
#opening file
abalone=pd.read_csv("abalone_csv.csv")
abalone.head()

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell_weight  Class_number_of_rings  
0         0.150                     15  
1         0.070                      7  
2         0.210                      9  
3         0.155                     10  
4         0.055                      7

In [71]:
abalone=abalone.drop("Sex",axis=1)

In [72]:
import numpy as np
X=abalone.drop("Class_number_of_rings",axis=1)
X=X.to_numpy()
X


array([[0.455 , 0.365 , 0.095 , ..., 0.2245, 0.101 , 0.15  ],
       [0.35  , 0.265 , 0.09  , ..., 0.0995, 0.0485, 0.07  ],
       [0.53  , 0.42  , 0.135 , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.6   , 0.475 , 0.205 , ..., 0.5255, 0.2875, 0.308 ],
       [0.625 , 0.485 , 0.15  , ..., 0.531 , 0.261 , 0.296 ],
       [0.71  , 0.555 , 0.195 , ..., 0.9455, 0.3765, 0.495 ]])

In [73]:
y=abalone['Class_number_of_rings']
y=y.to_numpy()
y

array([15,  7,  9, ...,  9, 10, 12], dtype=int64)

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=1234)

In [75]:
from sklearn.neighbors import KNeighborsRegressor
knn_model=KNeighborsRegressor(n_neighbors=3)

In [76]:
g=knn_model.fit(X_train,y_train)
g

KNeighborsRegressor(n_neighbors=3)

In [77]:

pred=g.predict(X_test)
pred

array([ 8.33333333, 14.        ,  5.66666667,  9.        ,  4.        ,
       13.        ,  8.        ,  9.33333333,  6.66666667,  8.33333333,
        6.33333333,  7.        , 10.66666667,  7.33333333, 10.33333333,
       10.33333333,  8.33333333,  7.33333333,  9.66666667,  9.33333333,
        9.66666667,  7.66666667, 11.33333333,  7.        , 10.66666667,
       11.33333333, 11.66666667,  9.        ,  7.33333333,  7.66666667,
       13.33333333,  7.        ,  7.        ,  9.66666667,  8.66666667,
        6.        , 10.        , 14.66666667,  3.33333333, 10.        ,
       12.66666667,  8.33333333,  8.66666667, 10.66666667, 14.66666667,
        6.33333333, 12.        ,  7.66666667, 10.33333333, 10.        ,
        8.33333333,  6.33333333,  8.33333333,  8.66666667, 11.        ,
       11.33333333, 14.33333333,  6.        ,  6.        ,  7.        ,
       10.        , 13.33333333, 10.33333333,  4.66666667, 11.        ,
        9.        , 13.66666667,  6.66666667, 10.        ,  7.33